# Netlify configuration for DesignsTouch AI Analysis

[build]
  # No build command needed - static HTML site
  publish = "."

[build.environment]
  # Node version (if needed for any future enhancements)
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets for 1 year
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  # Redirect root to index.html (default behavior)
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # SPA-style routing - serve index.html for any path
  from = "/*"
  to = "/index.html"
  status = 200
